SCREEN_WIDTH = 832
SCREEN_HEIGHT = 512
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

TILE_WIDTH = 64
TILE_HEIGHT = 64
TILE_SIZE = (TILE_WIDTH, TILE_HEIGHT)

FPS = 40

SCENE_ID_CURRENT = "current"
SCENE_ID_LOGIN = "login"
SCENE_ID_START = "start"
SCENE_ID_LEVEL = "level"
SCENE_ID_LOSE = "lose"
SCENE_ID_WIN = "win"
